### ISSUE TITLE
[Question] Prod/ in base url required

### ISSUE THREAD

**Issue by Avariya** [mnapoli/bref-symfony-demo#4]
Hi, Matthieu

as a user I can see https://x3em6yt28b.execute-api.us-east-1.amazonaws.com/Prod/ is available for everyone, it means lambda and layer works successfully.
But if you will add any link at this application - url generated by Symfony will look like https://x3em6yt28b.execute-api.us-east-1.amazonaws.com/about what is 404 as Prod/ is not part of path. I can not find any way how to set prefix at UrlGenerator, maybe you have some ideas?
I can see prefix in Kernel at https://github.com/mnapoli/mnapoli.github.io/blob/master/src/Kernel.php#L62, but it not helped me a lot.
Thank you in advance.

Also it is 403 for https://x3em6yt28b.execute-api.us-east-1.amazonaws.com/favicon.ico (as Prod/ not used and favicon.ico was not uploaded to S3 and assets are not configured for new setup, but I will try to resolve it locally after solution for current issue will be found)

**Comment by mnapoli** [comment]
Hi, this is probably an issue that is worth opening in the main Bref project.

**Comment by Avariya** [comment]
I did it here because I feel like:
* UrlGeneration can be fixed at Symfony side, but I did not found how to yet.
* Assets can be fixed by CI (moving assets to S3) and Symfony Assets configuration (set up assets cdn) 

If you will close this issue - I will create a new one at mnapoli/bref.

**Comment by mnapoli** [comment]
Right. This repository is a demo so nobody is following this repository.

**Comment by KorvinSzanto** [comment]
Just in case anyone else stumbles upon this, my fix was just to force the `HTTP_HOST` and `HTTPS` `$_SERVER` variables to be my domain and https, not necessarily ideal but it works. I added this to my `index.php` after the dotenv load:
```php
// Allow .env based override of server variables.
foreach ($_SERVER as $key => $value) {
    if (substr($key, 0, 9) === 'OVERRIDE_') {
        $_SERVER[substr($key, 9)] = $value;
    }
}
```
and added to `.env.prod`:
```bash
OVERRIDE_HTTP_HOST=example.com:443
OVERRIDE_HTTPS=on
```
